DROP TABLE IF EXISTS students;
CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    last_name TEXT NOT NULL,
    first_name TEXT NOT NULL,
    middle_name TEXT,
    suffix TEXT,
    birth_date TEXT,
    sex TEXT,
    mobile_number TEXT,
    email TEXT,
    home_address TEXT,
    guardian_name TEXT,
    guardian_mobile TEXT,
    last_school_attended TEXT,
    shs_strand TEXT,
    college TEXT,
    program TEXT,
    year_level INTEGER DEFAULT 1,
    block_section TEXT,
    student_type TEXT DEFAULT 'REGULAR',
    created_at TEXT DEFAULT (datetime('now'))
);
